(function(){var h={},mt={},c={id:"fa6e6bb6843b9cbe6d214d5a30d59a2a",dm:["changsha0731.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'/hmt/icon/22|gif|20|20',ctrk:[],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'F42F2437A717E060',conv:0,med:0,cvcc:'',cvcf:[],apps:'siteId=4488777&goTop=1'};var r=void 0,u=!0,v=null,w=!1;mt.cookie={};mt.cookie.set=function(a,b,d){var e;d.N&&(e=new Date,e.setTime(e.getTime()+d.N));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.Gc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:v};
mt.cookie.bc=function(a,b){try{var d="Hm_ck_"+ +new Date;mt.cookie.set(d,"is-cookie-enabled",{domain:a,path:b,N:r});var e="is-cookie-enabled"===mt.cookie.get(d)?"1":"0";mt.cookie.set(d,"",{domain:a,path:b,N:-1});return e}catch(k){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ta=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.F=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.D=function(a,b){var d=w;if(a==v||!mt.lang.d(a,"Array")||b===r)return d;if(Array.prototype.indexOf)d=-1!==a.indexOf(b);else for(var e=0;e<a.length;e++)if(a[e]===b){d=u;break}return d};mt.url={};mt.url.j=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:v};
mt.url.Cc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:v};mt.url.Gb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):v};mt.url.Q=function(a){return(a=mt.url.Gb(a))?a.replace(/:\d+$/,""):a};mt.url.pa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};mt.url.Ua=function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)};
mt.url.wa=function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length};
(function(){var a=mt.lang,b=mt.url;mt.g={};mt.g.yb=function(d){return document.getElementById(d)};mt.g.na=function(d){if(!d)return v;try{d=String(d);if(0===d.indexOf("!HMCQ!"))return d;if(0===d.indexOf("!HMCC!"))return document.querySelector(d.substring(6,d.length));for(var e=d.split(">"),a=document.body,b=e.length-1;0<=b;b--)if(-1<e[b].indexOf("#")){var f=e[b].split("#")[1];(a=document.getElementById(f))||(a=document.getElementById(decodeURIComponent(f)));e=e.splice(b+1,e.length-(b+1));break}for(d=
0;a&&d<e.length;){var l=String(e[d]).toLowerCase();if(!("html"===l||"body"===l)){var b=0,n=e[d].match(/\[(\d+)\]/i),f=[];if(n)b=n[1]-1,l=l.split("[")[0];else if(1!==a.childNodes.length){for(var s=0,t=0,m=a.childNodes.length;t<m;t++){var x=a.childNodes[t];1===x.nodeType&&x.nodeName.toLowerCase()===l&&s++;if(1<s)return v}if(1!==s)return v}for(s=0;s<a.childNodes.length;s++)1===a.childNodes[s].nodeType&&a.childNodes[s].nodeName.toLowerCase()===l&&f.push(a.childNodes[s]);if(!f[b])return v;a=f[b]}d++}return a}catch(g){return v}};
mt.g.pa=function(a,e){var b=[],p=[];if(!a)return p;for(;a.parentNode!=v;){for(var f=0,l=0,n=a.parentNode.childNodes.length,s=0;s<n;s++){var t=a.parentNode.childNodes[s];if(t.nodeName===a.nodeName&&(f++,t===a&&(l=f),0<l&&1<f))break}if((n=""!==a.id)&&e){b.unshift("#"+encodeURIComponent(a.id));break}else n&&(n="#"+encodeURIComponent(a.id),n=0<b.length?n+">"+b.join(">"):n,p.push(n)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+l+"]":""));a=a.parentNode}p.push(b.join(">"));return p};
mt.g.qa=function(a){return(a=mt.g.pa(a,u))&&a.length?String(a[0]):""};mt.g.Jb=function(a){return mt.g.pa(a,w)};mt.g.zb=function(a){var e;for(e="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==e)return a;return v};mt.g.Cb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.g.Hb=function(a){var e={top:0,left:0};if(!a)return e;var b=mt.g.Cb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(e=a.getBoundingClientRect());return{top:e.top+(window.pageYOffset||b.scrollTop)-
(b.clientTop||0),left:e.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.g.getAttribute=function(a,e){var b=a.getAttribute&&a.getAttribute(e)||v;if(!b&&a.attributes&&a.attributes.length)for(var p=a.attributes,f=p.length,l=0;l<f;l++)p[l].nodeName===e&&(b=p[l].nodeValue);return b};mt.g.P=function(a){var e="document";a.tagName!==r&&(e=a.tagName);return e.toLowerCase()};mt.g.Nb=function(b){var e="";b.textContent?e=a.trim(b.textContent):b.innerText&&(e=a.trim(b.innerText));e&&(e=e.replace(/\s+/g,
" ").substring(0,255));return e};mt.g.O=function(d,e){var k;a.F(d)&&0===String(d).indexOf("!HMCQ!")?(k=String(d),k=b.j(document.location.href,k.substring(6,k.length))):a.F(d)||(k=mt.g.P(d),"input"===k&&e&&("button"===d.type||"submit"===d.type)?k=a.trim(d.value)||"":"input"===k&&!e&&"password"!==d.type?k=a.trim(d.value)||"":"img"===k?(k=mt.g.getAttribute,k=k(d,"alt")||k(d,"title")||k(d,"src")):k="body"===k||"html"===k?["(hm-default-content-for-",k,")"].join(""):mt.g.Nb(d));return String(k||"").substring(0,
255)};(function(){(mt.g.fc=function(){function a(){if(!a.ba){a.ba=u;for(var b=0,e=p.length;b<e;b++)p[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(k){setTimeout(b,1);return}a()}var k=w,p=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,w);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!k)if(k=u,"complete"===document.readyState)a.ba=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var l=w;try{l=window.frameElement==v}catch(n){}document.documentElement.doScroll&&l&&b()}})();return function(b){a.ba?b():p.push(b)}}()).ba=w})();return mt.g})();mt.event={};
mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,w)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};
(function(){var a=mt.event;mt.f={};mt.f.Sa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.Bc=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.f.Dc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return w}};mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();
mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.hc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.Lb=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.f.Pa=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.f.C=
function(){return mt.f.Lb()+mt.f.Pa()};mt.f.ib=0;mt.f.Pb=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function b(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.f.orientation=a;mt.f.ib=mt.f.Pb()}b();a.e(window,"orientationchange",b)})();return mt.f})();mt.G={};
mt.G.parse=function(a){return(new Function("return ("+a+")"))()};
mt.G.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===v)return"null";if(e instanceof Array){var d=["["],p=e.length,f,l,n;for(l=0;l<p;l++)switch(n=e[l],typeof n){case "undefined":case "function":case "unknown":break;default:f&&d.push(","),d.push(mt.G.stringify(n)),f=1}d.push("]");return d.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';f=["{"];l=mt.G.stringify;for(p in e)if(Object.prototype.hasOwnProperty.call(e,p))switch(n=
e[p],typeof n){case "undefined":case "unknown":case "function":break;default:d&&f.push(","),d=1,f.push(l(p)+":"+l(n))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.ga=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return w}return u};
mt.localStorage.set=function(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ga()&&(mt.localStorage.l.expires=e.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ga())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(e){}return v};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ga())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):v}catch(b){return v}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.fb={};mt.fb.log=function(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=function(){d.onload=v;d=window[e]=v;b&&b(a)};d.src=a};mt.gb={};
mt.gb.Ob=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
h.s={Wb:"http://tongji.baidu.com/hm-web/welcome/ico",ab:"hm.baidu.com/hm.gif",ob:/^(tongji|hmcdn).baidu.com$/,sc:"tongji.baidu.com",Tb:"hmmd",Ub:"hmpl",vc:"utm_medium",Sb:"hmkw",xc:"utm_term",Qb:"hmci",uc:"utm_content",Vb:"hmsr",wc:"utm_source",Rb:"hmcu",tc:"utm_campaign",M:0,J:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",xa:"https:",Ec:0,zc:6E5,Fc:6E5,ic:5E3,Ac:5,Ma:1024,yc:1,za:2147483647,hb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
R:u,Ja:["a","input","button"],Ga:{id:"data-hm-id",W:"data-hm-class",V:"data-hm-xpath",content:"data-hm-content",da:"data-hm-tag",link:"data-hm-link"},Ia:"data-hm-enabled",Ha:"data-hm-disabled",ec:"https://hmcdn.baidu.com/static/tongji/plugins/",$a:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={B:{},e:function(a,d){this.B[a]=this.B[a]||[];this.B[a].push(d)},K:function(a,d){this.B[a]=this.B[a]||[];for(var e=this.B[a].length,k=0;k<e;k++)this.B[a][k](d)}};return h.t=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,d={Bb:function(a){var b;try{b=JSON.parse(decodeURIComponent(a[0]))}catch(d){}return b},Va:function(a,b){return d.Wa(h.c&&h.c.b&&h.c.b.u,a,b)||d.Wa(document.location.href,a,b)},Wa:function(a,d,p){if(a===r)return w;b.test(d)||(a=a.replace(b,""));d=d.replace(/\/$/,"");a=a.replace(/\/$/,"");p&&(a=a.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+d.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(a)},Z:function(b,k){var p=d.Bb(b);if(!a.d(p,
"Undefined")){if(a.d(p,"Array")){for(var f=0;f<p.length;f++)if(d.Va(p[f],k))return u;return w}if(a.d(p,"Object")){var f=[],l;for(l in p)p.hasOwnProperty(l)&&d.Va(l,k)&&(f=f.concat(p[l]));return f}}}};return h.ka=d})();
(function(){function a(a,e){var k=document.createElement("script");k.charset="utf-8";b.d(e,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=v,e()}:k.onload=function(){e()});k.src=a;var p=document.getElementsByTagName("script")[0];p.parentNode.insertBefore(k,p)}var b=mt.lang;return h.load=a})();
(function(){var a=h.s,b={init:function(){if(""!==c.icon){var b=c.icon.split("|"),e=a.Wb+"?s="+c.id,k="https://hmcdn.baidu.com/static"+b[0]+".gif";document.write("swf"===b[1]||"gif"===b[1]?'<a href="'+e+'" target="_blank"><img border="0" src="'+k+'" width="'+b[2]+'" height="'+b[3]+'"></a>':'<a href="'+e+'" target="_blank">'+b[0]+"</a>")}}};h.t.e("pv-b",b.init);return b})();
(function(){var a=mt.url,b=mt.cookie,d=mt.localStorage,e=mt.sessionStorage,k={getData:function(a){try{return b.get(a)||e.get(a)||d.get(a)}catch(f){}},setData:function(a,f,l){try{b.set(a,f,{domain:k.$(),path:k.ma(),N:l}),l?d.set(a,f,l):e.set(a,f)}catch(n){}},removeData:function(a){try{b.set(a,"",{domain:k.$(),path:k.ma(),N:-1}),e.remove(a),d.remove(a)}catch(f){}},$:function(){for(var b=document.location.hostname,e=0,d=c.dm.length;e<d;e++)if(a.wa(b,c.dm[e]))return c.dm[e].replace(/(:\d+)?[/?#].*/,"");
return b},ma:function(){for(var b=0,e=c.dm.length;b<e;b++){var d=c.dm[b];if(-1<d.indexOf("/")&&a.Ua(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.X=k})();
(function(){var a=mt.lang,b=mt.G,d=h.X,e={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},k={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},p=["session","user"],f="Hm_up_"+c.id,l={init:function(){l.Zb()},Zb:function(){try{var n=b.parse(decodeURIComponent(d.getData(f)));a.d(n,"Object")&&(e.user=n)}catch(s){}},w:function(a){var b={};e[a]!==r&&(b=e[a]);a=this.ra();for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a},ra:function(){for(var a={},b,d=p.length-
1;0<=d;d--){b=e[p[d]];for(var m in b)b.hasOwnProperty(m)&&(a[m]=b[m])}return a},setProperty:function(d,f,k){var m=e[d];if(a.d(m,"Object")&&a.d(f,"Object")){for(var x in f)if(f.hasOwnProperty(x)){var g=a.h(String(x));if(k||!/^_/.test(g)&&!/_$/.test(g)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(g)){var q=f[x];if(q==v)delete m[g];else{if(a.d(q,"Object")||a.d(q,"Array"))q=b.stringify(q);q=a.h(String(q));l.ac(d,g,q)&&(m[g]={value:q,scope:l.Oa(d)})}}}"user"===d&&l.Ba()}},n:function(b){b!==r&&("userId"===
b&&a.d(e.user,"Object")?(delete e.user.uid_,l.Ba()):"user"===b&&a.d(e.user,"Object")?(b=e.user.uid_,e.user=b===r?{}:{uid_:b},l.Ba()):e[b]!==r&&(e[b]={}))},Ba:function(){try{d.setData(f,encodeURIComponent(b.stringify(e.user)),c.age)}catch(a){}},ac:function(a,b,d){var m=u,f=e[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(d)).length)m=w;else{var g=f[b];f[b]={value:d,scope:l.Oa(a)};a=l.I(l.w(a));2048<encodeURIComponent(a).length&&(g!==r?f[b]=g:delete f[b],m=w)}return m},
I:function(a){var b=[],e,d;for(d in a)a.hasOwnProperty(d)&&(e=[d,a[d].value],(1===a[d].scope||2===a[d].scope)&&e.push(a[d].scope),b.push(e.join("*")));return b.join("!")},Oa:function(a){a=k[a];return a!==r?a:k.others}};return h.L=l})();
(function(){var a=mt.g,b=mt.lang,d=h.t,e=h.ka,k=h.L,p=k.I;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var f={Za:{},ea:{},init:function(){for(var a,d=e.Z(c.cptrk)||[],k=0;k<d.length;k++)if(a=d[k],a.a!==r&&b.d(a.a,"Object")){a=a.a;for(var p in a)a.hasOwnProperty(p)&&(f.ea[p]=String(a[p]))}},Ya:function(){var b,e,d;for(d in f.ea)if(f.ea.hasOwnProperty(d)&&f.Za[d]===r&&(b=f.ea[d],b=a.na(b)))e=e===r?{}:e,e[d]=a.O(b,w),f.Za[d]=u;return e},ta:function(){var a=f.Ya();a&&f.kc(a)},Yb:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(f.ta)).observe(document.body,{childList:u,subtree:u}):window.setInterval(f.ta,15E3)},kc:function(a){if(b.d(a,"Object")){k.setProperty("pageview",a);a=h.c.b.p;var e=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=p(k.w("pageview"));h.c.m();h.c.b.p=a;h.c.b.ep=e;k.n("pageview")}}};f.init();d.e("pv-b",function(){var a=f.Ya();a&&k.setProperty("pageview",a)});f.Yb();a.fc(f.ta)}})();
(function(){var a=mt.lang,b=mt.g,d=h.ka,e={Y:function(a,p){return function(f){var l=f.target||f.srcElement;if(l){var n=d.Z(p)||[],s=l.getAttribute(a.fa);f=f.clientX+":"+f.clientY;if(s&&s===f)l.removeAttribute(a.fa);else if(0<n.length&&(l=b.Jb(l))&&l.length)if(n=l.length,s=l[l.length-1],1E4>n*s.split(">").length)for(s=0;s<n;s++)e.eb(a,l[s]);else e.eb(a,s)}}},eb:function(b,e){for(var d={},l=String(e).split(">").length,n=0;n<l;n++)d[e]="",e=e.substring(0,e.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.Ka)&&
b.Ka(d)},gc:function(a,b){return function(e){(e.target||e.srcElement).setAttribute(a.fa,e.clientX+":"+e.clientY);a&&a.o&&(b?a.o(b):a.o("#"+encodeURIComponent(this.id),e.type))}}};return h.ub=e})();
(function(){var a=mt.g,b=mt.event,d=mt.lang,e=h.s,k=h.ka,p=h.ub,f=h.L,l=f.I,n={fa:"HM_ce",jb:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",p.Y(n,c.cetrk));for(var e=k.Z(c.cetrk)||[],d=0,m=e.length;d<m;d++){var f=e[d],g=f.p||"";-1===g.indexOf(">")&&(0===g.indexOf("#")&&(g=g.substring(1)),(g=a.yb(g))&&b.e(g,"click",p.gc(n,f)))}}},Ka:function(a){for(var b=k.Z(c.cetrk)||[],e=0;e<b.length;e++){var d=b[e],g=n.Eb(d.p,a);g&&n.o(d,g)}},Eb:function(a,b){a=String(a);if(0<a.indexOf("*")){var e=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),d;for(d in b)if(b.hasOwnProperty(d)&&e.test(d))return d;return v}return b.hasOwnProperty(a)?a:v},o:function(b,e){h.c.b.et=7;var m=b&&b.k||"",m=d.h(m),k={};if(b&&b.a&&d.d(b.a,"Object")){var g=b.a,q;for(q in g)if(g.hasOwnProperty(q)){var y=n.Kb(g[q]||"",e),y=y?a.O(y,w):"";k[q]=y}}k=n.Ab(k,e||b&&b.p);k._iden=m;f.setProperty("customEvent",k);h.c.b.ep="";h.c.b.p=l(f.w("customEvent"));h.c.m();h.c.b.p="";f.n("customEvent")},
Ab:function(b,d){var m=a.na(d),f=e.Ga;m&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(m,f.id)||a.getAttribute(m,"id")||"",b.ec_=a.getAttribute(m,f.W)||a.getAttribute(m,"class")||"",b.ex_=a.getAttribute(m,f.V)||a.qa(m),b.en_=a.getAttribute(m,f.content)||a.O(m,u),b.et_=a.getAttribute(m,f.da)||a.P(m),b.el_=a.getAttribute(m,f.link)||a.getAttribute(m,"href")||""):(b.ex_=a.getAttribute(m,f.V)||a.qa(m),b.en_=a.getAttribute(m,f.content)||a.O(m,u)));return b},Kb:function(b,e){b=String(b);e=String(e);if(0<b.indexOf("*")){var d=
/.*\[(\d+)\]$/.exec(e);b=b.replace("*",d?d[1]:"1")}return a.na(b)}};h.t.e("pv-b",n.jb);return n})();
(function(){var a=mt.lang,b=mt.g,d=mt.event,e=mt.f,k=h.s,p=h.t,f=h.L,l=f.I,n=+new Date,s=[],t={Y:function(){return function(e){if(h.c&&h.c.R&&c.aet&&c.aet.length){var d=e.target||e.srcElement;if(d){var g=h.c.Ja,q=b.getAttribute(d,k.Ia)!=v?u:w;if(b.getAttribute(d,k.Ha)==v)if(q)t.ha(t.oa(d,e));else{var f=b.P(d);if(a.D(g,"*")||a.D(g,f))t.ha(t.oa(d,e));else for(;d.parentNode!=v;){var q=d.parentNode,f=b.P(q),z="a"===f&&a.D(g,"a")?u:w,f="button"===f&&a.D(g,"button")?u:w,A=b.getAttribute(q,k.Ia)!=v?u:w;
if(b.getAttribute(q,k.Ha)==v&&(z||f||A)){t.ha(t.oa(q,e));break}d=d.parentNode}}}}}},oa:function(d,f){var g={},q=k.Ga;g.id=b.getAttribute(d,q.id)||b.getAttribute(d,"id")||"";g.W=b.getAttribute(d,q.W)||b.getAttribute(d,"class")||"";g.V=b.getAttribute(d,q.V)||b.qa(d);g.content=b.getAttribute(d,q.content)||b.O(d,u);g.da=b.getAttribute(d,q.da)||b.P(d);g.link=b.getAttribute(d,q.link)||b.getAttribute(d,"href")||"";g.type=f.type||"click";q=a.Ta(d.offsetTop)?d.offsetTop:0;"click"===f.type?q=e.Sa?f.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):f.pageY:"touchend"===f.type&&(f.Xa&&f.Xa.changedTouches)&&(q=f.Xa.changedTouches[0].pageY);g.rc=q;q=this.Db(f);g.ya=q.ya||0;g.Aa=q.Aa||0;g.Fa=q.Fa||0;g.sa=q.sa||0;g.Da=q.Da||"b";return g},Db:function(d){var f=d.target||d.srcElement,g;if(e.Sa){var q=Math.max(document.documentElement.scrollTop,document.body.scrollTop);g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);g=d.clientX+g;d=d.clientY+q}else g=d.pageX,
d=d.pageY;var k=q=0,z=0,A=0;if(f&&(q=f.offsetWidth||f.clientWidth,k=f.offsetHeight||f.clientHeight,A=b.Hb(f),z=A.left,A=A.top,a.d(f.getBBox,"Function")&&(k=f.getBBox(),q=k.width,k=k.height),"html"===(f.tagName||"").toLowerCase()))q=Math.max(q,f.clientWidth),k=Math.max(k,f.clientHeight);return{ya:Math.round(100*((g-z)/q)),Aa:Math.round(100*((d-A)/k)),Fa:q,sa:k,Da:("a"===(f.tagName||"").toLowerCase()?f:b.zb(f))?"a":"b"}},ha:function(b){var d=a.h;b=[+new Date-(h.c.S!==r?h.c.S:n),d(b.id),d(b.W),d(b.da),
d(b.V),d(b.link),d(b.content),b.type,b.rc,b.ya,b.Aa,b.Fa,b.sa,b.Da].join("*");t.ia(b);a.d(this.U(),"Function")&&this.U()()},ia:function(a){var b=k.Ma;a.length>b||(encodeURIComponent(s.join("!")+a).length>b&&0<s.length&&(t.o(s.join("!")),s=[]),s.push(a))},o:function(a){h.c.b.et=5;h.c.b.ep=a;f.setProperty("autoEventTracking",{view_h_:e.C()},u);h.c.b.p=l(f.w("autoEventTracking"));h.c.m();h.c.b.p="";f.setProperty("autoEventTracking",{view_h_:v},u)},U:function(){return function(){s&&s.length&&(t.o(s.join("!")),
s=[])}}};a.F(c.aet)&&""!==c.aet&&p.e("pv-b",function(){d.e(document,"click",t.Y());"ontouchend"in document&&d.e(window,"touchend",t.Y());d.e(window,"unload",t.U())});return t})();
(function(){var a=mt.lang,b=mt.event,d=mt.f,e=h.s,k=h.t,p=h.L,f=p.I,l=+new Date,n=[],s=v,t={mb:function(){a.F(c.aet)&&""!==c.aet&&setInterval(t.cb,e.ic)},cb:function(){var a=d.C();0<a-h.c.b.vl&&(h.c.b.vl=a)}},m={tb:function(){return function(){h.c&&(h.c.R&&c.aet&&c.aet.length)&&(window.clearTimeout(s),s=window.setTimeout(function(){m.lb(d.C())},150))}},lb:function(a){m.ia([+new Date-(h.c.S!==r?h.c.S:l),a].join("*"))},ia:function(a){if(encodeURIComponent(n.join("!")+a).length>e.Ma||3<n.length)m.o(n.join("!")),
n=[];n.push(a)},o:function(a){t.cb();h.c.b.et=6;h.c.b.vh=d.Pa();h.c.b.ep=a;p.setProperty("autoEventTracking",{view_h_:d.C()},u);h.c.b.p=f(p.w("autoEventTracking"));h.c.m();h.c.b.p="";p.setProperty("autoEventTracking",{view_h_:v},u)},U:function(){return function(){n&&n.length&&(m.o(n.join("!")),n=[])}}};a.F(c.aet)&&""!==c.aet&&k.e("pv-b",function(){b.e(window,"scroll",m.tb());b.e(window,"unload",m.U());t.mb()});return m})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.la.Ib()+","+h.la.Fb();h.c.b.hca=c.hca;h.c.m()}}function b(){clearTimeout(z);var a;q&&(a="visible"==document[q]);y&&(a=!document[y]);l="undefined"==typeof a?u:a;if((!f||!n)&&l&&s)g=u,m=+new Date;else if(f&&n&&(!l||!s))g=w,x+=+new Date-m;f=l;n=s;z=setTimeout(b,100)}function d(a){var b=document,q="";if(a in b)q=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var f=d[e]+a.charAt(0).toUpperCase()+a.slice(1);
if(f in b){q=f;break}}return q}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))s="focus"==a.type||"focusin"==a.type?u:w,b()}var k=mt.event,p=h.t,f=u,l=u,n=u,s=u,t=+new Date,m=t,x=0,g=u,q=d("visibilityState"),y=d("hidden"),z;b();(function(){var a=q.replace(/[vV]isibilityState/,"visibilitychange");k.e(document,a,b);k.e(window,"pageshow",b);k.e(window,"pagehide",b);"object"==typeof document.onfocusin?(k.e(document,"focusin",e),k.e(document,"focusout",e)):(k.e(window,
"focus",e),k.e(window,"blur",e))})();h.la={Ib:function(){return+new Date-t},Fb:function(){return g?+new Date-m+x:x}};p.e("pv-b",function(){k.e(window,"unload",a())});p.e("duration-send",a());p.e("duration-done",function(){m=t=+new Date;x=0});return h.la})();
(function(){var a=mt.lang,b=h.s,d=h.load,e=h.X,k={Xb:function(k){if((window._dxt===r||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var f=e.$();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),k)}},qc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.rb=k})();
(function(){function a(a,b,d,e){if(!(a===r||b===r||e===r)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var f,g=w,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=d;f[2]=e;a[k]=f.join("*");g=u;break}g||a.push([b,d,e].join("*"));return a.join("!")}}function b(a){for(var d in a)if({}.hasOwnProperty.call(a,d)){var f=a[d];e.d(f,"Object")||e.d(f,"Array")?b(f):a[d]=String(f)}}var d=mt.url,e=mt.lang,k=mt.G,p=mt.f,f=h.s,l=h.t,n=h.rb,s=h.load,t=h.X,m=h.L,x=m.I,g={T:[],ca:0,va:w,
A:{Ea:"",page:""},init:function(){g.i=0;m.init();l.e("pv-b",function(){g.sb();g.vb()});l.e("pv-d",function(){g.wb();g.A.page=""});l.e("stag-b",function(){h.c.b.api=g.i||g.ca?g.i+"_"+g.ca:"";h.c.b.ct=[decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),g.A.Ea,g.A.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;g.i=0;g.ca=0})},sb:function(){var a=window._hmt||[];if(!a||e.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var d=arguments[b];
e.d(d,"Array")&&(a.cmd[a.id].push(d),"_setAccount"===d[0]&&(1<d.length&&/^[0-9a-f]{31,32}$/.test(d[1]))&&(d=d[1],a.id=d,a.cmd[d]=a.cmd[d]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},vb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,e=0,f=b.length;e<f;e++){var k=b[e];d.test(k[0])?g.T.push(k):g.Ca(k)}a.cmd[c.id]={push:g.Ca}},wb:function(){if(0<g.T.length)for(var a=0,b=g.T.length;a<b;a++)g.Ca(g.T[a]);g.T=v},Ca:function(a){var b=
a[0];if(g.hasOwnProperty(b)&&e.d(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(g.i|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||u===a))g.i|=2,h.c.Qa=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(g.i|=4,h.c.b.sn=h.c.Na(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=p.C(),h.c.b.kb=0,h.c.ua?(h.c.b.nv=0,h.c.b.st=4):h.c.ua=u,g.va||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=f.protocol+"//"+document.location.host+
a[1],h.c.b.p=x(m.w("pageview")),h.c.m(),h.c.b.p="",h.c.S=+new Date,m.n("pageview"))},_trackEvent:function(a){2<a.length&&(g.i|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=e.h(a[1])+"*"+e.h(a[2])+(a[3]?"*"+e.h(a[3]):"")+(a[4]?"*"+e.h(a[4]):""),h.c.b.p=x(m.ra()),h.c.m(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){g.ca++;for(var f=(h.c.b.cv||"*").split("!"),k=f.length;k<b-1;k++)f.push("*");f[b-1]=d+"*"+e.h(a[2])+"*"+e.h(a[3]);h.c.b.cv=f.join("!");
a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?t.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):t.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==r&&b!==r){var f=decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),f=a(f,d,1,b);t.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==r&&b!==r){var f=g.A.Ea,f=a(f,d,2,b);g.A.Ea=f}}},_setPageTag:function(b){if(!(3>
b.length)){var d=e.h(b[1]);b=e.h(b[2]);if(d!==r&&b!==r){var f=g.A.page,f=a(f,d,3,b);g.A.page=f}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],e.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?f.protocol+"//"+window.location.host+a:a,g.va=u):g.va=w)},_trackOrder:function(a){a=a[1];e.d(a,"Object")&&(b(a),g.i|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=k.stringify(a),h.c.b.p=x(m.ra()),h.c.m(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.i|=
32,h.c.b.et=93,h.c.b.ep=a,h.c.m()},_setDataxId:function(a){a=a[1];n.Xb();n.qc(a)},_setUserId:function(a){a=a[1];if(a!==r&&(e.F(a)||e.Ta(a))){var b=m.w("user").uid_;if(!(b&&b.value===e.h(String(a)))){var b=h.c.b.p,d=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+e.h(String(a));h.c.m();var f={};f.uid_=a;m.setProperty("user",f,u);h.c.b.p=b;h.c.b.ep=d}}},_clearUserId:function(a){1<a.length&&u===a[1]&&m.n("userId")},_setUserProperty:function(a){a=a[1];e.d(a,"Object")&&m.setProperty("user",a)},_clearUserProperty:function(a){1<
a.length&&u===a[1]&&m.n("user")},_setSessionProperty:function(a){a=a[1];e.d(a,"Object")&&m.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&m.n("session")},_setPageviewProperty:function(a){a=a[1];e.d(a,"Object")&&m.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&m.n("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];e.d(a,"Object")&&m.setProperty("autoEventTracking",a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&
u===a[1]&&m.n("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.Ra=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.R=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.m())):l.K("duration-send");l.K("duration-done")},_require:function(a){1<a.length&&(a=a[1],f.ob.test(d.Q(a))&&s(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1];a=a[2];if(e.D(f.$a,
d)&&e.d(a,"Function")&&(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[d]=a,b.z=b.z||[],a=b.z.slice(),d&&a.length&&a[0][1]===d))for(var g=0,k=a.length;g<k;g++){var l=a[g][2]||{};if(b.plugins[d]&&!b.H[d])b.H[d]=new b.plugins[d](l),b.z.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],k=a[2]||{};if(e.D(f.$a,d))if(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[d]&&!b.H[d])b.H[d]=new b.plugins[d](k);else{b.z=b.z||[];for(var k=0,l=b.z.length;k<l;k++)if(b.z[k][1]===
d)return;b.z.push(a);g._require([v,f.ec+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];e.d(a,"Object")||(a={});a._iden=b;m.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=x(m.w("customEvent"));h.c.m();h.c.b.p="";m.n("customEvent")}}};g.init();h.pb=g;return h.pb})();
(function(){var a=h.t;c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Ra=this.Qa=u,this.R=g.R,this.Ja=k.F(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.ua=w,this.init())}var b=mt.url,d=mt.fb,e=mt.gb,k=mt.lang,p=mt.cookie,f=mt.f,l=mt.sessionStorage,n=mt.G,s=mt.event,t=h.X,m=h.L,x=m.I,g=h.s,q=h.load,y=h.t;a.prototype={aa:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(b.Ua(a,c.dm[d]))return u}else{var e=b.Q(a);if(e&&b.wa(e,
c.dm[d]))return u}return w},Mb:function(){if(!document.referrer)return g.J-g.M>c.vdur?1:4;var a=w;this.aa(document.referrer)&&this.aa(document.location.href)?a=u:(a=b.Q(document.referrer),a=b.wa(a||"",document.location.hostname));return a?g.J-g.M>c.vdur?1:4:3},nc:function(){var a,b,d,e,f,k;g.M=t.getData("Hm_lpvt_"+c.id)||0;13===g.M.length&&(g.M=Math.round(g.M/1E3));b=this.Mb();a=4!==b?1:0;if(k=t.getData("Hm_lvt_"+c.id)){e=k.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<g.J-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(g.J);4<e.length;)e.shift();k=e.join(",");e=e[e.length-1]}else k=g.J,e="",f=1;this.$b()?(t.setData("Hm_lvt_"+c.id,k,c.age),t.setData("Hm_lpvt_"+c.id,g.J),d=p.bc(t.$(),t.ma())):this.xb();if(0===c.nv&&this.aa(document.location.href)&&(""===document.referrer||this.aa(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},$b:function(){var a=b.Q(document.location.href);return!k.D("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},xb:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&t.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&t.removeData(d[0])}},mc:function(){for(var a=[],b=this.b.et,d=0,e=g.hb.length;d<e;d++){var f=g.hb[d],k=this.b[f];"undefined"!==typeof k&&""!==k&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(k))}return a.join("&")},pc:function(){this.nc();
this.b.si=c.id;this.b.sn=this.Na();this.b.su=document.referrer;this.b.ds=f.hc;this.b.cl=f.colorDepth+"-bit";this.b.ln=String(f.language).toLowerCase();this.b.ja=f.javaEnabled?1:0;this.b.ck=f.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=e.Ob();this.b.v="1.2.89";this.b.cv=decodeURIComponent(t.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=f.C();var a=document.location.href;this.b.cm=b.j(a,g.Tb)||"";this.b.cp=b.j(a,g.Ub)||b.j(a,g.vc)||"";this.b.cw=b.j(a,g.Sb)||
b.j(a,g.xc)||"";this.b.ci=b.j(a,g.Qb)||b.j(a,g.uc)||"";this.b.cf=b.j(a,g.Vb)||b.j(a,g.wc)||"";this.b.cu=b.j(a,g.Rb)||b.j(a,g.tc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.pc(),0===this.b.nv?this.lc():this.La(),h.c=this,this.qb(),this.dc(),y.K("pv-b"),this.jc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(g.xa+"//"+g.ab+"?"+
b.join("&"))}},jc:function(){function a(){y.K("pv-d")}this.Qa?(this.ua=u,this.b.et=0,this.b.ep="",this.b.p=x(m.w("pageview")),this.b.vl=f.C(),this.m(a),this.b.p=""):a();this.S=+new Date;m.n("pageview")},m:function(a){if(this.Ra){var b=this;b.b.rnd=Math.round(Math.random()*g.za);b.b.r=f.orientation;b.b.ww=f.ib;y.K("stag-b");var e=g.xa+"//"+g.ab+"?"+b.mc();y.K("stag-d");b.nb(e);d.log(e,function(d){b.bb(d);k.d(a,"Function")&&a.call(b)})}},qb:function(){try{if(window.postMessage&&window.self!==window.parent){var a=
this;s.e(window,"message",function(d){if(b.Q(d.origin)===g.sc){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$|^select$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*g.za),q(g.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},dc:function(){try{if(window.self===window.parent){var a=document.location.href,d=b.j(a,"baidu-analytics-token"),e=b.j(a,"baidu-analytics-jn");
/^[a-f0-9]{32}\/?$/.test(d)&&/^overlay\/?$/.test(e)&&q(g.protocol+"//"+c.js+e+".js?"+Math.round(Math.random()*g.za))}}catch(f){}},nb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,n.stringify(b))},bb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,
"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,n.stringify(b)):this.La()}},La:function(){l.remove("Hm_unsent_"+c.id)},lc:function(){var a=this,b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length)for(var f=function(b){d.log(g.xa+"//"+b,function(b){a.bb(b)})},k=0;k<b.length;k++)f(b[k])},Na:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.s,C=h.load;
if(c.apps){var D=[B.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);C(D.join(""))}var E=h.s,F=h.load;c.pt&&F([E.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));var G=h.load;if(c.qiao){for(var H=["https://goutong.baidu.com/site/"],I=c.id,J=5381,K=I.length,L=0;L<K;L++)J=(33*J+Number(I.charCodeAt(L)))%4294967296;2147483648<J&&(J-=2147483648);H.push(J%1E3+"/");H.push(c.id+"/b.js");H.push("?siteId="+c.qiao);G(H.join(""))};})();
